### ISSUE TITLE
map layers

### ISSUE THREAD

**Issue by jueyang** [cristinafurlong/roadscholarnyc#3]
There will be 3 layers in total.
## School layer, points

When you click on a school:
- [x] enrollment 
- [x] precinct name and grades. requires a spatial join.
## UPK, points

When you click on a UPK:
- [x] enrollment 
- [x] precinct name and grades
## Afterschool, points

When you click on an afterschool program:
- [x] as is
## Precinct, polygon
- [x] as is 
# Next actions:
1. Join school location + enrollment  -- @jueyang
2. Spatially join school + precinct -- @cristinafurlong 
3. Spatially join UPK + precinct -- @cristinafurlong 
4. Develop UI for clicking points and toggling precinct boundaries -- @jueyang

**Comment by jueyang** [comment]
@cristinafurlong Steps to add a `precinct` code to school and UPK dataset: https://gist.github.com/jueyang/2225d9beb357359a677e

**Comment by jueyang** [comment]
Here's the school location layer with enrollment. https://jue.cartodb.com/tables/school_clean_geo_merge/public/map

Now that you have all layers that you think will be useful, it's time to look into making an interface with it.

**Comment by cristinafurlong** [comment]
Will make an interface with different symbologies. School, UPK, and Afterschool. Clicking on them will show precinct borders and school, numbers and contacts. Cris will invite someone for the demo.

**Comment by jueyang** [comment]
@cristinafurlong Can you download the school data from the link in the previous comment and upload that to your account? 

This will help keep things in one place and for me to write more consistent code.

**Comment by cristinafurlong** [comment]
Yes. What format?

**Comment by jueyang** [comment]
Download/upload it as csv is fine.

**Comment by jueyang** [comment]
Also, I don't see the preccint dataset in your account. Could you point me to it?

**Comment by jueyang** [comment]
(Disregard my comment on precinct. I found it under `soj_nypp`)

**Comment by cristinafurlong** [comment]
Hi Jue,
It's uploaded. Thanks!

**Comment by jueyang** [comment]
I noticed there's no precinct associated with schools & UPK. However this might not be a big problem if we veer towards the new workflow in #5.

We'll need some data cleaning/organizing in general for this project, but that's another ticket for this week. Closing here.

**Comment by cristinafurlong** [comment]
I can't seem to find the final merged bit.
