### ISSUE TITLE
UI for navigating the map

### ISSUE THREAD

**Issue by jueyang** [cristinafurlong/roadscholarnyc#4]
Develop UI for:
- [x] clicking point layers (school, UPK, after school)
- [ ] toggling precinct boundaries

ref #3

**Comment by jueyang** [comment]
@cristinafurlong The preliminary map is on http://cristinafurlong.github.io/roadscholarnyc/

After investigating the precincts, I don't think toggling makes that much sense. Since there are only 16 precincts in Queens, here is what I think facilitates a better user flow:
1. A parent clicks on precinct to get info on total school/UPK/afterschool counts, plus the aggregated student enrollment for that precinct. 
2. S/he then proceed to "view details" of that precinct.
3. If s/he hovers over precinct, the respective precinct gets highlighted.

I'll try to make the above user flow happen by the demo tmrw. But if not, we can chat after (esp. if your community members are coming, they might have some great feedback) and prep for the next class (where we talk about where things can go, etc.)

**Comment by jueyang** [comment]
Tracking #5. Closing

**Comment by cristinafurlong** [comment]
Thanks, in class tonight. Will look at it later. sounds good.
